### ISSUE TITLE
Keep getting ERR_REQUIRE_ESM errors in logs

### ISSUE THREAD

**Issue by mmattbtw** [noiredayz/trilaud#4]
![image](https://user-images.githubusercontent.com/30363562/147899012-c4f6ec5f-28b8-479b-af46-712168682383.png)

I'm using node 16, any ideas on why this is happening? Just trying to run it on my local raspberry pi.

**Comment by noiredayz** [comment]
I upgraded deps without testing them again Pepega FBBlok 🧠 
Chalk 5.x no longer supports common js and needs to be used as ESM. Ref: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

For now I downgraded Chalk in deps to 4.x so it works again. Future rewrite will be needed to ESM support, it's not the first time I get them.
Resolved in https://github.com/noiredayz/trilaud/commit/e452d8a21a2cbbba711f14084a589d955818dd54
